baseURL = "https://blog.ropnop.com"

DefaultContentLanguage = "en"
title = "ropnop blog"
theme = "beautifulhugo-ropnop"
metaDataFormat = "yaml"

#pygmentsStyle = "manni"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
pygmentsOptions = "linenos=table"
disqusShortname = "ropnopblog"
googleAnalytics = "UA-76398957-1"

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 1

[permalinks]
  post = "/:slug"

[taxonomies]
  series = "series"
  tags = "tags"

[Params]
  homeTitle = "ropnop blog" # Set a different text for the header on the home page
  subtitle = "A place to dump things I find interesting and think others might want to know"
  mainSections = ["post","posts"]
  logo = "images/ropnop.jpg" # Expecting square dimensions
  favicons = "images/favicons/"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = false
  wordCount = false
  useHLJS = false
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = false
  shareBaseURL = "https://blog.ropnop.com"


[Author]
  name = "ropnop"
  website = "blog.ropnop.com"
  email = "rflathers@gmail.com"
  github = "ropnop"
  twitter = "ropnop"
  

[[menu.main]]
    name = "Posts"
    url = ""
    weight = 1

[[menu.main]]
    identifier = "talks"
    name = "Conference Talks"
    url = "talk"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    name = "Series"
    url = "series"
    weight = 4



