baseurl = "/"
DefaultContentLanguage = "en"
title = "ropnop blog"
theme = "beautifulhugo-ropnop"
metaDataFormat = "yaml"

pygmentsStyle = "monokai"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 1

[permalinks]
  post = "/:slug"

[taxonomies]
  series = "series"

[Params]
  homeTitle = "ropnop blog" # Set a different text for the header on the home page
  subtitle = "A place to dump things I find interesting and think others might want to know"
  mainSections = ["post","posts"]
  logo = "images/ropnop.jpg" # Expecting square dimensions
  favicons = "images/favicons/"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = false


[Author]
  name = "ropnop"
  website = "blog.ropnop.com"
  email = "rflathers@gmail.com"
  github = "ropnop"
  twitter = "ropnop"
  

[[menu.main]]
    name = "Posts"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    name = "Series"
    url = "series"
    weight = 3