name: Publish Blog

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: amondnet/now-deployment@v2
      if: github.ref == 'refs/heads/master'
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        zeit-token: ${{secrets.ZEIT_TOKEN}}
        now-org-id: ${{secrets.ORG_ID}}
        now-project-id: ${{secrets.PROJECT_ID}}
        now-args: "--prod -c"
    - uses: amondnet/now-deployment@v2
      if: github.ref != 'refs/heads/master'
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        zeit-token: ${{secrets.ZEIT_TOKEN}}
        now-org-id: ${{secrets.ORG_ID}}
        now-project-id: ${{secrets.PROJECT_ID}}
        now-args: "-c -b BASE_URL=/"
