name: Publish Blog

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - if: github.ref == 'refs/heads/master'
      run: echo "::set-output name=nowargs::--prod"
      id: prodcheck
    - uses: amondnet/now-deployment@v1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        zeit-token: ${{secrets.ZEIT_TOKEN}}
        now-args: ${{ steps.prodcheck.outputs.nowargs }}
