name: Publish Blog

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: amondnet/vercel-action@v19
      if: github.ref == 'refs/heads/master'
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        vercel-token: ${{secrets.VERCEL_TOKEN}}
        vercel-org-id: ${{secrets.ORG_ID}}
        vercel-project-id: ${{secrets.PROJECT_ID}}
        vercel-args: "--prod -c"
    - uses: amondnet/vercel-action@v19
      if: github.ref != 'refs/heads/master'
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        vercel-token: ${{secrets.VERCEL_TOKEN}}
        vercel-org-id: ${{secrets.ORG_ID}}
        vercel-project-id: ${{secrets.PROJECT_ID}}
        vercel-args: "-c -b BASE_URL=/"
