name: Publish Blog

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: amondnet/now-deployment@v1
      if: github.ref == 'refs/heads/master
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        zeit-token: ${{secrets.ZEIT_TOKEN}}
        now-args: "--prod"
    - uses: amondnet/now-deployment@v1
      if: github.ref != 'refs/heads/master'
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        zeit-token: ${{secrets.ZEIT_TOKEN}}
        now-args: '-b "/"'
