name: Publish Blog

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: amondnet/now-deployment@v1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        zeit-token: ${{secrets.ZEIT_TOKEN}}
        now-args: '--prod'
